WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/lanxiang/anaconda3/envs/llm_train/bin/python: can't open file '/NFS/home/lanxiang/MIT/LLMs_and_TVM/layerwise_condense/Sapling/run_clm_llama_lwcd_static_sparse.py': [Errno 2] No such file or directory
/home/lanxiang/anaconda3/envs/llm_train/bin/python: can't open file '/NFS/home/lanxiang/MIT/LLMs_and_TVM/layerwise_condense/Sapling/run_clm_llama_lwcd_static_sparse.py': [Errno 2] No such file or directory
/home/lanxiang/anaconda3/envs/llm_train/bin/python: can't open file '/NFS/home/lanxiang/MIT/LLMs_and_TVM/layerwise_condense/Sapling/run_clm_llama_lwcd_static_sparse.py': [Errno 2] No such file or directory
/home/lanxiang/anaconda3/envs/llm_train/bin/python: can't open file '/NFS/home/lanxiang/MIT/LLMs_and_TVM/layerwise_condense/Sapling/run_clm_llama_lwcd_static_sparse.py': [Errno 2] No such file or directory
/home/lanxiang/anaconda3/envs/llm_train/bin/python: can't open file '/NFS/home/lanxiang/MIT/LLMs_and_TVM/layerwise_condense/Sapling/run_clm_llama_lwcd_static_sparse.py': [Errno 2] No such file or directory
/home/lanxiang/anaconda3/envs/llm_train/bin/python: can't open file '/NFS/home/lanxiang/MIT/LLMs_and_TVM/layerwise_condense/Sapling/run_clm_llama_lwcd_static_sparse.py': [Errno 2] No such file or directory
/home/lanxiang/anaconda3/envs/llm_train/bin/python: can't open file '/NFS/home/lanxiang/MIT/LLMs_and_TVM/layerwise_condense/Sapling/run_clm_llama_lwcd_static_sparse.py': [Errno 2] No such file or directory
/home/lanxiang/anaconda3/envs/llm_train/bin/python: can't open file '/NFS/home/lanxiang/MIT/LLMs_and_TVM/layerwise_condense/Sapling/run_clm_llama_lwcd_static_sparse.py': [Errno 2] No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 933307) of binary: /home/lanxiang/anaconda3/envs/llm_train/bin/python
Traceback (most recent call last):
  File "/home/lanxiang/anaconda3/envs/llm_train/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/lanxiang/anaconda3/envs/llm_train/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/lanxiang/anaconda3/envs/llm_train/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/lanxiang/anaconda3/envs/llm_train/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/lanxiang/anaconda3/envs/llm_train/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lanxiang/anaconda3/envs/llm_train/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_llama_lwcd_static_sparse.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-16_02:13:14
  host      : L1.MIT.EDU
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 933308)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-11-16_02:13:14
  host      : L1.MIT.EDU
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 933309)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-11-16_02:13:14
  host      : L1.MIT.EDU
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 933310)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2023-11-16_02:13:14
  host      : L1.MIT.EDU
  rank      : 4 (local_rank: 4)
  exitcode  : 2 (pid: 933311)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2023-11-16_02:13:14
  host      : L1.MIT.EDU
  rank      : 5 (local_rank: 5)
  exitcode  : 2 (pid: 933312)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2023-11-16_02:13:14
  host      : L1.MIT.EDU
  rank      : 6 (local_rank: 6)
  exitcode  : 2 (pid: 933313)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2023-11-16_02:13:14
  host      : L1.MIT.EDU
  rank      : 7 (local_rank: 7)
  exitcode  : 2 (pid: 933314)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-16_02:13:14
  host      : L1.MIT.EDU
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 933307)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
