WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/transformers/training_args.py:1516: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead 
  warnings.warn(
/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/transformers/training_args.py:1516: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead 
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/transformers/training_args.py:1516: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead 
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/transformers/training_args.py:1516: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead 
  warnings.warn(
/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/transformers/training_args.py:1516: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead 
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/transformers/training_args.py:1516: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead 
  warnings.warn(
/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/transformers/training_args.py:1516: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead 
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/transformers/training_args.py:1516: FutureWarning: using `--fsdp_transformer_layer_cls_to_wrap` is deprecated. Use fsdp_config instead 
  warnings.warn(
04/19/2024 09:14:27 - WARNING - __main__ - Process rank: 5, device: cuda:5, n_gpu: 1distributed training: True, 16-bits training: False
04/19/2024 09:14:27 - WARNING - __main__ - Process rank: 6, device: cuda:6, n_gpu: 1distributed training: True, 16-bits training: False
Last Checkpoint: None
Traceback (most recent call last):
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 734, in <module>
Last Checkpoint:    main() 
None
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 436, in main
    raise ValueError(
ValueError: Output directory (outputs/TheBloke/Llama-2-7B-fp16/sciq_bs_3/decomposition_7) already exists and is not empty. Use --overwrite_output_dir to overcome.
Traceback (most recent call last):
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 734, in <module>
    main()
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 436, in main
    raise ValueError(
ValueError: Output directory (outputs/TheBloke/Llama-2-7B-fp16/sciq_bs_3/decomposition_7) already exists and is not empty. Use --overwrite_output_dir to overcome.
04/19/2024 09:14:27 - WARNING - __main__ - Process rank: 3, device: cuda:3, n_gpu: 1distributed training: True, 16-bits training: False
Last Checkpoint: None
Traceback (most recent call last):
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 734, in <module>
    main()
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 436, in main
    raise ValueError(
ValueError: Output directory (outputs/TheBloke/Llama-2-7B-fp16/sciq_bs_3/decomposition_7) already exists and is not empty. Use --overwrite_output_dir to overcome.
04/19/2024 09:14:27 - WARNING - __main__ - Process rank: 2, device: cuda:2, n_gpu: 1distributed training: True, 16-bits training: False
Last Checkpoint: None
Traceback (most recent call last):
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 734, in <module>
    main()
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 436, in main
    raise ValueError(
ValueError: Output directory (outputs/TheBloke/Llama-2-7B-fp16/sciq_bs_3/decomposition_7) already exists and is not empty. Use --overwrite_output_dir to overcome.
04/19/2024 09:14:27 - WARNING - __main__ - Process rank: 7, device: cuda:7, n_gpu: 1distributed training: True, 16-bits training: False
Last Checkpoint: None
Traceback (most recent call last):
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 734, in <module>
    main()
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 436, in main
    raise ValueError(
ValueError: Output directory (outputs/TheBloke/Llama-2-7B-fp16/sciq_bs_3/decomposition_7) already exists and is not empty. Use --overwrite_output_dir to overcome.
04/19/2024 09:14:27 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
04/19/2024 09:14:27 - INFO - __main__ - Training/evaluation parameters TrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=True,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=epoch,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[<FSDPOption.FULL_SHARD: 'full_shard'>, <FSDPOption.AUTO_WRAP: 'auto_wrap'>],
fsdp_config={'fsdp_min_num_params': 0, 'fsdp_transformer_layer_cls_to_wrap': ['LlamaDecoderLayer'], 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=LlamaDecoderLayer,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=2e-05,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=outputs/TheBloke/Llama-2-7B-fp16/sciq_bs_3/decomposition_7/runs/Apr19_09-14-27_lambda-blade-03,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=32.0,
optim=adamw_hf,
optim_args=None,
output_dir=outputs/TheBloke/Llama-2-7B-fp16/sciq_bs_3/decomposition_7,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=3,
per_device_train_batch_size=3,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=False,
report_to=[],
resume_from_checkpoint=True,
run_name=outputs/TheBloke/Llama-2-7B-fp16/sciq_bs_3/decomposition_7,
save_on_each_node=False,
save_safetensors=False,
save_steps=20000,
save_strategy=steps,
save_total_limit=1,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
Last Checkpoint: None
Traceback (most recent call last):
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 734, in <module>
    main()
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 436, in main
    raise ValueError(
ValueError: Output directory (outputs/TheBloke/Llama-2-7B-fp16/sciq_bs_3/decomposition_7) already exists and is not empty. Use --overwrite_output_dir to overcome.
04/19/2024 09:14:27 - WARNING - __main__ - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: False
Last Checkpoint: None
Traceback (most recent call last):
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 734, in <module>
    main()
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 436, in main
    raise ValueError(
ValueError: Output directory (outputs/TheBloke/Llama-2-7B-fp16/sciq_bs_3/decomposition_7) already exists and is not empty. Use --overwrite_output_dir to overcome.
04/19/2024 09:14:27 - WARNING - __main__ - Process rank: 4, device: cuda:4, n_gpu: 1distributed training: True, 16-bits training: False
Last Checkpoint: None
Traceback (most recent call last):
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 734, in <module>
    main()
  File "/home/ubuntu/luke/Sapling/scripts/run_decomposition.py", line 436, in main
    raise ValueError(
ValueError: Output directory (outputs/TheBloke/Llama-2-7B-fp16/sciq_bs_3/decomposition_7) already exists and is not empty. Use --overwrite_output_dir to overcome.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 468830) of binary: /home/ubuntu/anaconda3/envs/trimllama/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/trimllama/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/anaconda3/envs/trimllama/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_decomposition.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-04-19_09:14:29
  host      : lambda-blade-03
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 468831)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-04-19_09:14:29
  host      : lambda-blade-03
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 468832)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-04-19_09:14:29
  host      : lambda-blade-03
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 468834)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-04-19_09:14:29
  host      : lambda-blade-03
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 468835)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-04-19_09:14:29
  host      : lambda-blade-03
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 468836)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-04-19_09:14:29
  host      : lambda-blade-03
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 468837)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-04-19_09:14:29
  host      : lambda-blade-03
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 468839)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-19_09:14:29
  host      : lambda-blade-03
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 468830)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
